/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.armakuni.playground

data class Message(val message: String)

data class User(val name: String)

class SocialNetwork {
    private var messages: MutableMap<User, List<Message>> = mutableMapOf()
    fun postMessage(user: User, message: Message) = messages.compute(user) { _, userMessages -> userMessages.orEmpty() + message }
    fun getUserTimelineMessages(user: User): List<Message> = messages[user].orEmpty()
}
