/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.armakuni.playground

data class Message(val message: String)

data class UserName(val name: String)

class User(val name: UserName) {
    private var messages: List<Message> = listOf()

    fun postMessage(message: Message) {
        messages += message
    }

    fun getMessages(): List<Message> {
        return messages
    }
}



class SocialNetwork {
    private var messages: MutableMap<UserName, List<Message>> = mutableMapOf()
    private var userSubscriptions: MutableMap<UserName, Set<UserName>> = mutableMapOf()
    private var users: MutableMap<UserName, User> = mutableMapOf()

    fun postMessage(userName: UserName, message: Message) {
        if (userName !in users) {
            users[userName] = User(userName)
        }

        users[userName]?.postMessage(message)
        messages.compute(userName) { _, userMessages -> userMessages.orEmpty() + message }
    }

    fun getUserTimelineMessagesOld(user: UserName): List<Message> = messages[user].orEmpty()

    fun getUserTimelineMessages(userName: UserName): List<Message> {
        return users[userName]?.getMessages().orEmpty()
    }

    fun subscribeUser(userSubscribing: UserName, userSubscribingTo: UserName) {
        userSubscriptions.compute(userSubscribing) { _, usersExistingSubscriptions -> usersExistingSubscriptions.orEmpty() + userSubscribingTo }
    }

    fun getSubscriptionMessagesForUser(user: UserName): List<Message> {
        val usersExistingSubscriptions = userSubscriptions[user]

        val usersSubscriptionMessages = mutableListOf<Message>()
        for (user in usersExistingSubscriptions.orEmpty().iterator()) {
            usersSubscriptionMessages += messages[user].orEmpty()
        }
        return usersSubscriptionMessages
    }
}
