/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.armakuni.playground

import kotlin.test.Test
import kotlin.test.assertEquals

class SocialNetworkTest {
    @Test fun `a gets an empty list when they have not posted an messages`() {
        val socialNetwork = SocialNetwork()

        val timeline = socialNetwork.getUserTimelineMessages(User("Alice"))

        assertEquals(listOf(), timeline)
    }

    @Test fun `a user can get their timeline`() {
        val socialNetwork = SocialNetwork()

        socialNetwork.postMessage(User("Alice"), Message("hello"))

        val timeline = socialNetwork.getUserTimelineMessages(User("Alice"))

        assertEquals(listOf(Message("hello")), timeline)
    }

    @Test fun `a user can get a multiple messages from their timeline`() {
        val socialNetwork = SocialNetwork()

        socialNetwork.postMessage(User("Alice"), Message("hello, for the first time"))
        socialNetwork.postMessage(User("Alice"), Message("hello, again"))

        val timeline = socialNetwork.getUserTimelineMessages(User("Alice"))

        assertEquals(listOf(Message("hello, for the first time"), Message("hello, again")), timeline)
    }

    @Test fun `users can only see messages from themselves in their timeline`() {
        val socialNetwork = SocialNetwork()

        socialNetwork.postMessage(User("Alice"), Message("hello, for the first time"))
        socialNetwork.postMessage(User("Bob"), Message("hello, again"))

        val alicesTimeline = socialNetwork.getUserTimelineMessages(User("Alice"))
        val bobsTimeline = socialNetwork.getUserTimelineMessages(User("Bob"))

        assertEquals(listOf(Message("hello, for the first time")), alicesTimeline)
        assertEquals(listOf(Message("hello, again")), bobsTimeline)
    }
}

